data<-read.table(file.choose(),sep=";",header = T)
data[,1]<-as.Date(data[,1],format = "%d/%m/%Y")
library(hms)
data[,2]<-parse_hms(data[,2])
input<-(data[,1]>="2007-02-01" & data[,1]<="2007-02-02")
finaldata<-data[input,]
finaldata$Global_active_power<-as.numeric(finaldata$Global_active_power)
finaldata$Time<-paste(finaldata$Date,finaldata$Time)
finaldata$Time<-as.POSIXct(finaldata$Time)
png(file="plot3.png")
par(lwd=1)
plot(finaldata$Time,finaldata$Sub_metering_1,type = "l", ylab = "Energy sub metering",xlab="")
points(finaldata$Time,finaldata$Sub_metering_2,col="red",type = "l")
points(finaldata$Time,finaldata$Sub_metering_3,col="blue",type = "l")
legend("topright",lty = 1,col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()